export interface Tool {
  id: number
  name: string
  logo: string
  category: string
  summary: string
  features: string[]
  website: string
  featured?: boolean
}

export const toolsData: Tool[] = [
  {
    id: 1,
    name: "Motion",
    logo: "https://company-images.partnerstack.com/file_cjK8yuRdkwf8tPSQxhHO.png",
    category: "Productivity",
    summary:
      "AI-powered productivity app that auto-schedules tasks, manages projects and calendars, and integrates notes and docs to help teams save 25% more time.",
    features: ["AI auto-scheduling", "Project management", "Calendar integration", "Notes & docs", "Task automation"],
    website: "https://usemotion.com",
    featured: true,
  },
  {
    id: 2,
    name: "Prezi",
    logo: "https://company-images.partnerstack.com/file_7jl92qwdTXfw6YYNDKZp.png",
    category: "Design",
    summary:
      "Prezi is an AI presentation tool that helps you stand out, bring your ideas to life, and create interactive presentations easier than ever.",
    features: [
      "AI presentation builder",
      "Interactive design",
      "Engaging visuals",
      "Collaboration tools",
      "Creative templates",
    ],
    website: "https://prezi.com",
    featured: true,
  },
  {
    id: 3,
    name: "Databox",
    logo: "https://company-images.partnerstack.com/file_t1esaScaBNrFZJjPnWpv.png",
    category: "Analytics",
    summary:
      "Databox is modern BI software for teams that need answers now. It offers the best of BI, without the complicated setup, steep price, or long learning curve.",
    features: [
      "Unlimited dashboards",
      "Data visualization",
      "Automated reporting",
      "Goal-setting",
      "Advanced analytics",
    ],
    website: "https://databox.com",
  },
  {
    id: 4,
    name: "Tiki",
    logo: "https://company-images.partnerstack.com/file_fp4aj0PSq1SApPr3TOkv.jpeg",
    category: "Analytics",
    summary: "Tiki unlocks value for businesses by bringing new data products to market.",
    features: ["Data products", "Business insights", "Market analysis", "Data monetization", "Analytics platform"],
    website: "https://tiki.ai",
  },
  {
    id: 5,
    name: "Confido Health",
    logo: "https://company-images.partnerstack.com/file_qKtypynj711wKqG3TTap.png",
    category: "AI Voice & Audio",
    summary:
      "Confido Health's 24/7 Healthcare Voice AI Agents work alongside your team, handling calls and updating your EHR/PMS in real time.",
    features: [
      "24/7 AI voice agents",
      "EHR/PMS integration",
      "Call automation",
      "Patient coordination",
      "Healthcare workflows",
    ],
    website: "https://confidohealth.com",
    featured: true,
  },
  {
    id: 6,
    name: "TTSOpenAI",
    logo: "https://company-images.partnerstack.com/file_w2AB3ilkeLHrnUAzPU4O.jpeg",
    category: "AI Voice & Audio",
    summary:
      "TTSOpenAI converts text into lifelike speech. Transform PDFs, DOCX files, and eBooks into MP3s (audiobooks) with natural voice output.",
    features: ["Text-to-speech", "PDF to audio", "eBook conversion", "40+ languages", "Natural voice output"],
    website: "https://ttsopenai.com",
  },
  {
    id: 7,
    name: "Vista Social",
    logo: "https://company-images.partnerstack.com/file_5HwUCY4jEGSS32pCUOHU.png",
    category: "Marketing",
    summary:
      "Fast-growing social media management platform with high conversion rates. 14-day free trial. 4.8/5 G2; 4.9/5 Capterra.",
    features: [
      "Social media scheduling",
      "Analytics dashboard",
      "Team collaboration",
      "Content management",
      "Multi-platform support",
    ],
    website: "https://vistasocial.com",
  },
  {
    id: 8,
    name: "Pilim",
    logo: "https://company-images.partnerstack.com/file_aQE3nh1QeWUVhYJAxAMJ.png",
    category: "Productivity",
    summary:
      "AI powered business management platform for SMEs and enterprises, streamlining cashflow, HR, asset management, and documents.",
    features: ["Cashflow management", "HR automation", "Asset tracking", "Document management", "Real-time insights"],
    website: "https://pilim.io",
  },
  {
    id: 9,
    name: "Bebop",
    logo: "https://company-images.partnerstack.com/file_C246cjzZ17uEuNPSeLzm.png",
    category: "Sales",
    summary:
      "Turn your network into revenue - powered by AI. Instantly surface leads, build prospect dossiers, and automate sales prep.",
    features: ["AI prospecting", "Lead generation", "Prospect dossiers", "Sales automation", "Network monetization"],
    website: "https://bebop.ai",
    featured: true,
  },
  {
    id: 10,
    name: "Rebolt",
    logo: "https://company-images.partnerstack.com/file_mmO7c5WybGr0PDaV8iNJ.jpeg",
    category: "Marketing",
    summary:
      "All-in-one marketing platform for home service businesses, offering SEO-optimized websites, social media management, and AI-powered content creation.",
    features: [
      "SEO-optimized websites",
      "Social media management",
      "AI content creation",
      "Home services focus",
      "Marketing automation",
    ],
    website: "https://rebolt.com",
  },
  {
    id: 11,
    name: "DataSnipper",
    logo: "https://company-images.partnerstack.com/file_zNhnbtuUbCXv8vnAUiE9.png",
    category: "Automation",
    summary:
      "Intelligent automation platform that automatically and securely extracts, cross-references and validates source documents of any audit and finance procedure.",
    features: ["Document extraction", "Data validation", "Cross-referencing", "Audit automation", "Finance procedures"],
    website: "https://datasnipper.com",
  },
  {
    id: 12,
    name: "Activepieces",
    logo: "https://company-images.partnerstack.com/file_t83pzVbMtqgAOgIKjlXO.jpeg",
    category: "Automation",
    summary: "Build AI agents and automations that connect apps, APIs, and data without heavy engineering.",
    features: ["AI agents", "No-code automation", "API integration", "Workflow builder", "Zapier alternative"],
    website: "https://activepieces.com",
  },
  {
    id: 13,
    name: "Distance",
    logo: "https://company-images.partnerstack.com/file_lXWgVElDQjKnZEvIrCiI.png",
    category: "Sales",
    summary:
      "AI Sales Platform built for service businesses. Capture more leads and book more jobs across channels 24/7.",
    features: [
      "AI sales platform",
      "24/7 lead capture",
      "Multi-channel support",
      "Job booking automation",
      "Service business focus",
    ],
    website: "https://distance.ai",
  },
  {
    id: 14,
    name: "Handover",
    logo: "https://company-images.partnerstack.com/file_WlhQfthr5OD5ozNJ9qWM.png",
    category: "Productivity",
    summary:
      "Enables teams to capture and transfer critical context and know-how through a guided handover process — key person departures, onboarding, project transitions.",
    features: [
      "Knowledge transfer",
      "Onboarding automation",
      "Project handovers",
      "Context preservation",
      "Team collaboration",
    ],
    website: "https://handover.ai",
  },
  {
    id: 15,
    name: "Interakt by Jio Haptik",
    logo: "https://company-images.partnerstack.com/file_dMn1H5QiQyChAvoQ5Ui0.png",
    category: "Marketing",
    summary:
      "Commerce platform that powers sales and support journeys across WhatsApp and Instagram, turning conversations into revenue.",
    features: [
      "WhatsApp commerce",
      "Instagram integration",
      "In-chat storefronts",
      "AI chatbots",
      "Meta solution provider",
    ],
    website: "https://interakt.shop",
  },
  {
    id: 16,
    name: "Devicie Inc.",
    logo: "https://company-images.partnerstack.com/file_uBJVVDx3Bz1bkHwDWTOl.png",
    category: "Automation",
    summary:
      "Automated, always optimized Intune deployment and maintenance at scale - so MSPs and IT teams can secure, manage, and grow without the grind.",
    features: ["Intune automation", "Deployment management", "MSP tools", "IT security", "Scale operations"],
    website: "https://devicie.com",
  },
  {
    id: 17,
    name: "BidX",
    logo: "https://company-images.partnerstack.com/file_HYuw2i7G30W0jGWkx7Vb.png",
    category: "Marketing",
    summary:
      "Seamless, AI-powered paid advertising platform for Amazon and Walmart sellers. Covers Sponsored Products, Display, DSP, and AMC.",
    features: ["Amazon advertising", "Walmart ads", "AI bid optimization", "Sponsored products", "DSP management"],
    website: "https://bidx.io",
  },
  {
    id: 18,
    name: "Creative Score",
    logo: "https://company-images.partnerstack.com/file_30Q3M94Fm41VULYps2Ky.jpeg",
    category: "Marketing",
    summary:
      "49% of Ad Performance is driven by creative quality. Diagnostic tool leveraging AI, behavioral science and real-world performance data.",
    features: [
      "Ad creative analysis",
      "AI diagnostics",
      "Performance optimization",
      "Behavioral science",
      "Creative testing",
    ],
    website: "https://creativescore.io",
  },
  {
    id: 19,
    name: "Mega HR",
    logo: "https://company-images.partnerstack.com/file_GWfeWaJObw7jlxbTesgZ.jpeg",
    category: "HR Tech",
    summary:
      "Mega plugs into your ATS to streamline and scale hiring with AI precision. Automate up to 78% of your busy work.",
    features: [
      "ATS integration",
      "AI hiring manager",
      "Recruitment automation",
      "Candidate screening",
      "Interview scheduling",
    ],
    website: "https://megahr.ai",
  },
  {
    id: 20,
    name: "Murf AI",
    logo: "https://company-images.partnerstack.com/file_On6oeRMiYpN22OrLGs32.jpeg",
    category: "AI Voice & Audio",
    summary:
      "Cloud-based realistic text-to-speech platform. AI and deep machine learning generate ultra-realistic voiceovers across 120+ voices in 20+ languages.",
    features: ["200+ AI voices", "30+ languages", "Voice styles", "Pronunciation control", "Emphasis & variability"],
    website: "https://murf.ai",
    featured: true,
  },
  {
    id: 21,
    name: "ClickUp",
    logo: "https://company-images.partnerstack.com/file_h5m8NRvunISw8BIYO3Sx.png",
    category: "Productivity",
    summary:
      "Versatile project management and productivity platform that centralizes tasks, docs, goals, and communication in one place.",
    features: ["Unlimited tasks", "Collaborative docs", "Kanban boards", "Sprint management", "Calendar view"],
    website: "https://clickup.com",
  },
  {
    id: 22,
    name: "Just Reach Out",
    logo: "https://company-images.partnerstack.com/file_XSYIHTX1NTw3w71blcjr.webp",
    category: "Marketing",
    summary:
      "AI-powered public relations software that helps businesses of all sizes efficiently and effectively earn press. 5,000+ customers with global journalist network.",
    features: ["AI-powered PR", "Journalist network", "Global outreach", "Press opportunities", "Media connections"],
    website: "https://justreachout.io",
  },
  {
    id: 23,
    name: "Skillfully",
    logo: "https://company-images.partnerstack.com/file_3bixlEbWm8qylazPRpBn.jpeg",
    category: "HR Tech",
    summary:
      "Skills-based hiring is transformative. Skillfully's AI-powered simulations show what candidates can actually do, helping build stronger teams.",
    features: [
      "Skills-based hiring",
      "AI simulations",
      "Dynamic assessments",
      "Candidate evaluation",
      "Lego LLM architecture",
    ],
    website: "https://skillfully.ai",
  },
  {
    id: 24,
    name: "MindStudio",
    logo: "https://company-images.partnerstack.com/file_w0fTbI30Xxcx3pMkR7tB.jpeg",
    category: "AI Development",
    summary: "Rapidly build AI agents with MindStudio's flexible and secure no-code platform.",
    features: ["No-code AI builder", "Unlimited custom agents", "Unlimited runs", "200+ AI models", "Service router"],
    website: "https://mindstudio.ai",
    featured: true,
  },
  {
    id: 25,
    name: "Vida Global Inc.",
    logo: "https://company-images.partnerstack.com/file_5uSggCwiTqXeFyO4mNpR.jpeg",
    category: "AI Voice & Audio",
    summary:
      "Vida.io's AI Phone Agents give businesses true 24/7 support across calls, SMS, email, and web chat in 10 languages.",
    features: ["AI phone agents", "Omnichannel support", "10 languages", "Call routing", "24/7 availability"],
    website: "https://vida.io",
  },
  {
    id: 26,
    name: "Motion App",
    logo: "https://company-images.partnerstack.com/file_NvSF39DwzzPYrG.jpeg",
    category: "Marketing",
    summary:
      "Learn which ad creatives are working best and share your findings with visual reports that are easy to digest.",
    features: [
      "Ad creative analytics",
      "Visual reporting",
      "Performance tracking",
      "Campaign insights",
      "Creative optimization",
    ],
    website: "https://motionapp.com",
  },
  {
    id: 27,
    name: "BLACKBOX AI",
    logo: "https://company-images.partnerstack.com/file_e9UmEGI5e9AYGZzRt27C.png",
    category: "AI Development",
    summary: "AI-powered coding assistant that helps developers write, search, and optimize code faster.",
    features: [
      "AI coding assistant",
      "All chat/image/video models",
      "Voice agent",
      "Code completion",
      "Multi-model access",
    ],
    website: "https://blackbox.ai",
  },
  {
    id: 28,
    name: "Logome.ai",
    logo: "https://company-images.partnerstack.com/file_bcbwi15zObfHkWGsgLf4.png",
    category: "Design",
    summary: "Create a logo and brand kit you'll love with Logome's AI logo generator.",
    features: ["AI logo maker", "Multiple file types", "Forever customization", "Brand kit", "Full ownership"],
    website: "https://logome.ai",
  },
  {
    id: 29,
    name: "Laxis",
    logo: "https://company-images.partnerstack.com/file_0zuhA8m8VaU3h5Mj8E9E.jpeg",
    category: "Sales",
    summary:
      "The Ultimate AI Assistant for Revenue Teams. 20,000+ professionals across 3,000+ organizations. AI Meeting Assistant and AI BDR streamline meetings and drive sales.",
    features: ["AI meeting assistant", "Transcription", "CRM integration", "Sales automation", "Revenue intelligence"],
    website: "https://laxis.com",
  },
  {
    id: 30,
    name: "Demodesk",
    logo: "https://company-images.partnerstack.com/file_DxifOZKLUEqEyeWE4nFu.png",
    category: "Sales",
    summary:
      "AI Agents that listen to sales conversations to automate manual work, coach sellers and generate critical insights.",
    features: ["AI sales agents", "Call recording", "AI transcription", "AI coaching", "CRM sync"],
    website: "https://demodesk.com",
  },
  {
    id: 31,
    name: "AiSDR, Inc.",
    logo: "https://company-images.partnerstack.com/file_wJ9VO6NnOnXcCvM0DgaG.jpeg",
    category: "Sales",
    summary:
      "First AI sales agent that handles entire outreach end-to-end with meaningful conversations through emails, LinkedIn, and text messages.",
    features: [
      "AI sales outreach",
      "Prospecting with AI",
      "Lead finder",
      "AI-researched emails",
      "LinkedIn automation",
    ],
    website: "https://aisdr.com",
  },
  {
    id: 32,
    name: "Castmagic",
    logo: "https://company-images.partnerstack.com/file_rSsGoVV3XPutxfjpEyG7.png",
    category: "Content Creation",
    summary: "Castmagic helps creators turn any form of audio into content, fast.",
    features: ["AI transcription", "60+ languages", "Magic Chat", "Longform AI", "Audiogram generation"],
    website: "https://castmagic.io",
  },
  {
    id: 33,
    name: "Looka",
    logo: "https://company-images.partnerstack.com/companyLogo/file_RFDWBKM1qbipVF.image/png",
    category: "Design",
    summary: "Help your friends make beautiful logos using AI and earn cash in return.",
    features: ["AI-powered logo design", "Unlimited changes", "Full ownership", "Hi-res & vector files", "Brand kit"],
    website: "https://looka.com",
  },
  {
    id: 34,
    name: "Runpod",
    logo: "https://company-images.partnerstack.com/file_caU02cKnUPOy9zUdjRVb.jpeg",
    category: "AI Development",
    summary:
      "Cloud platform that empowers small teams to deploy customized full-stack AI apps without managing complex infrastructure.",
    features: ["Cloud platform", "High-performance GPU", "Deploy AI apps", "Train models", "Optimize workloads"],
    website: "https://runpod.io",
  },
  {
    id: 35,
    name: "KrispCall",
    logo: "https://company-images.partnerstack.com/file_vhxhMQ14Sez5tSMDxSVr.png",
    category: "Communication",
    summary:
      "AI-powered Phone App designed for modern businesses. Get international virtual phone numbers and connect with global audiences remotely.",
    features: ["Cloud telephony", "Unified CallBox", "Call forwarding", "Call transfer", "Call center solution"],
    website: "https://krispcall.com",
  },
  {
    id: 36,
    name: "Capsule CRM",
    logo: "https://company-images.partnerstack.com/file_AA1d814sCrbmRCu4X5wA.png",
    category: "Sales",
    summary:
      "Help your customers grow their small businesses with a complete CRM and Marketing solution. Easy-to-implement and use CRM.",
    features: ["Contact management", "Sales pipeline", "Projects & tasks", "Automations", "Social campaigns"],
    website: "https://capsulecrm.com",
  },
  {
    id: 37,
    name: "Tidio",
    logo: "https://company-images.partnerstack.com/file_grcafbWzSPTJU377Cd1T.png",
    category: "Customer Support",
    summary:
      "Grow faster with AI-powered customer service. Tidio unifies Lyro AI Agent, live chat, ticketing, and automations in one inbox.",
    features: [
      "Customer service platform",
      "Lyro AI Agent",
      "Live chat & Ticketing",
      "Email management",
      "AI conversations",
    ],
    website: "https://tidio.com",
  },
  {
    id: 38,
    name: "Amplemarket",
    logo: "https://company-images.partnerstack.com/file_kFTEAVsIOeO5eyysmiLG.png",
    category: "Sales",
    summary:
      "Mission to help companies grow and do business smarter. All-in-one compound solution leveraging cutting-edge AI to streamline B2B sales.",
    features: ["Duo Copilot AI", "AI copywriter", "Competitive intelligence", "Buying signals", "Sales automation"],
    website: "https://amplemarket.com",
  },
  {
    id: 39,
    name: "SaneBox",
    logo: "https://company-images.partnerstack.com/file_2zQ7bXI222VKW6pPEOJd.png",
    category: "Productivity",
    summary:
      "Leading AI email productivity tool that saves users 12-14 hours a month on email time. Trusted by thousands of professionals.",
    features: ["Email deep clean", "Email organize", "Daily digest", "Smart folders", "Email reminders"],
    website: "https://sanebox.com",
  },
  {
    id: 40,
    name: "Assembly",
    logo: "https://company-images.partnerstack.com/file_wximXULl8dPyRc2sBSOg.png",
    category: "Customer Support",
    summary:
      "Assembly's product suite gives service businesses an all-in-one solution for client management, communication, payments, file-sharing, and contracts.",
    features: ["Employee recognition", "Celebrations", "Rewards", "Announcements", "Awards & Challenges"],
    website: "https://joinassembly.com",
  },
  {
    id: 41,
    name: "Explo",
    logo: "https://company-images.partnerstack.com/file_P2TLy4HWF5rYWmRLRzei.png",
    category: "Analytics",
    summary:
      "Explo helps companies embed customer-facing analytics seamlessly into their products. Deploy interactive dashboards and enable self-serve reporting.",
    features: [
      "Embedded analytics",
      "Interactive dashboards",
      "Self-serve reporting",
      "Real-time insights",
      "Report builder",
    ],
    website: "https://explo.co",
  },
  {
    id: 42,
    name: "Airia",
    logo: "https://company-images.partnerstack.com/file_xIhZrBdyvzIOfTKRK9Zf.png",
    category: "AI Development",
    summary:
      "Leading Enterprise AI Orchestration Platform, empowering organizations to securely build and manage AI solutions at scale.",
    features: [
      "Enterprise AI orchestration",
      "Agent orchestration",
      "Data integration",
      "AI platform",
      "Enterprise security",
    ],
    website: "https://airia.com",
  },
  {
    id: 43,
    name: "Volza",
    logo: "https://company-images.partnerstack.com/file_wsdbUZzgj5TRPVsPHmVl.png",
    category: "Analytics",
    summary:
      "Global trade-intelligence platform delivering verified export-import shipment data and actionable insights. 30+ years of heritage in trade analytics.",
    features: [
      "Export-import data",
      "203 countries coverage",
      "Global opportunity discovery",
      "Powerful search",
      "Trade analytics",
    ],
    website: "https://volza.com",
  },
  {
    id: 44,
    name: "Reclaim.ai",
    logo: "https://company-images.partnerstack.com/file_3h2qeo82lbBNaj1u1cC3.png",
    category: "Productivity",
    summary:
      "AI calendar that automatically protects focus time, optimizes your meetings, and improves your work-life balance. +30,000 signups/month!",
    features: ["Focus time", "Habits", "Tasks", "Smart meetings", "Scheduling links"],
    website: "https://reclaim.ai",
  },
  {
    id: 45,
    name: "Pangram Labs",
    logo: "https://company-images.partnerstack.com/file_7VJ6W9Hl3hP4tmM29FXX.png",
    category: "AI Development",
    summary:
      "Research-backed AI detection company that helps educators, content creators, and organizations create AI transparency.",
    features: ["AI detection", "Content verification", "Transparency tools", "Educational focus", "Organization tools"],
    website: "https://pangramlabs.com",
  },
  {
    id: 46,
    name: "Puzzle.io",
    logo: "https://company-images.partnerstack.com/file_fi7myYP1dQ5QGqjkISQN.png",
    category: "Productivity",
    summary:
      "Turn numbers into cash. Help businesses level up their accounting game. Stress-free cash and accrual accounting.",
    features: [
      "Cash accounting",
      "Accrual accounting",
      "Financial reports",
      "Accounting automation",
      "Business finance",
    ],
    website: "https://puzzle.io",
  },
  {
    id: 47,
    name: "ThorData",
    logo: "https://company-images.partnerstack.com/file_xyLC5i8txWHDKeJqRUrS.png",
    category: "Analytics",
    summary:
      "Cutting-edge ethical proxy network tailored to meet unique demands. 60M+ Residential IP pool with industry-leading features for global data access.",
    features: [
      "60M+ residential IPs",
      "Ethical proxy network",
      "Global coverage",
      "Public data access",
      "Business proxies",
    ],
    website: "https://thordata.com",
  },
  {
    id: 48,
    name: "DataHawk",
    logo: "https://company-images.partnerstack.com/file_v4YxyyeZmz9gc8I5qFgF.png",
    category: "Analytics",
    summary:
      "Brings together Amazon and Walmart data into an enterprise-grade platform. Executive-ready dashboards, daily alerts, and AI-powered insights.",
    features: ["Amazon analytics", "Walmart data", "Executive dashboards", "Performance alerts", "AI insights"],
    website: "https://datahawk.co",
  },
  {
    id: 49,
    name: "Snowfire AI",
    logo: "https://company-images.partnerstack.com/file_IItPCsuum8IZGb9M74aI.png",
    category: "AI Development",
    summary:
      "AI decision intelligence platform that fuses corporate & external data with military-grade precision for real-time, personalized insights.",
    features: ["Decision intelligence", "Real-time insights", "Risk mitigation", "Executive support", "Data fusion"],
    website: "https://snowfire.ai",
  },
  {
    id: 50,
    name: "Weave Communications",
    logo: "https://company-images.partnerstack.com/file_25MzEV3vUuT1bXg8GZEo.png",
    category: "Communication",
    summary:
      "All-in-one communications platform for texting, phone, scheduling, payments & more. Helping over 35K Dental, Vet, Optometry, & Medical practices.",
    features: ["Unified communications", "Text to pay", "Online bill pay", "Payment plans", "Medical practice tools"],
    website: "https://getweave.com",
  },
  {
    id: 51,
    name: "Smartli",
    logo: "https://company-images.partnerstack.com/file_3ukiUC3bNskh1jesgTIk.jpeg",
    category: "Content Creation",
    summary:
      "Maximize your e-commerce content with AI: text generator, essay writer, copy enhancer, rewriter, character creator, blogs, and ads.",
    features: ["SEO descriptions", "AI keywords", "AI blog writer", "AI ads writer", "Content generation"],
    website: "https://smartli.ai",
  },
  {
    id: 52,
    name: "Synthflow AI",
    logo: "https://company-images.partnerstack.com/file_lTSTOSuiCiq3t6kpZ22h.png",
    category: "AI Voice & Audio",
    summary:
      "No-code voice AI agent platform that automates customer interactions like appointment scheduling, lead qualification, and customer support.",
    features: [
      "Customer service automation",
      "Receptionist AI",
      "Voice support",
      "Multilingual support",
      "No-code platform",
    ],
    website: "https://synthflow.ai",
  },
  {
    id: 53,
    name: "Rank Prompt",
    logo: "https://company-images.partnerstack.com/file_ZwFyQ1XWRKklYaxcGTZ4.png",
    category: "Marketing",
    summary: "We give brands the tools they need to scale visibility in AI rankings.",
    features: ["AI rankings", "Multiple brands support", "Priority support", "Beta features", "Dashboard & exports"],
    website: "https://rankprompt.ai",
  },
  {
    id: 54,
    name: "ElevenLabs",
    logo: "https://company-images.partnerstack.com/file_nhuKnTPgdZWqMCMPRaPu.png",
    category: "AI Voice & Audio",
    summary: "ElevenLabs' AI Audio makes content accessible in any voice and language.",
    features: ["Text to speech", "Speech to text", "Music", "Agents", "Voice cloning"],
    website: "https://elevenlabs.io",
    featured: true,
  },
  {
    id: 55,
    name: "Hume AI",
    logo: "https://company-images.partnerstack.com/file_0KriPPapQWPXCF3VHaiU.png",
    category: "AI Voice & Audio",
    summary:
      "The empathic AI company. While other voice AI just 'reads' words, Hume's voices grasp meaning. Customize voices for any character.",
    features: [
      "Text-to-speech",
      "Speech-to-speech",
      "Expression measurement",
      "Conversational voice",
      "TTS creator studio",
    ],
    website: "https://hume.ai",
  },
  {
    id: 56,
    name: "Recomaze AI",
    logo: "https://company-images.partnerstack.com/file_rkU1c1LHt095Qeetl9C4.png",
    category: "Marketing",
    summary:
      "Turns any store into an AI Sales Agent. AI traffic, engagement, sales agent, memory-based personalization, and adaptive cross-sell.",
    features: [
      "AI sales agent",
      "Traffic optimization",
      "Brand-voice conversations",
      "Real-time guidance",
      "Checkout uplift",
    ],
    website: "https://recomaze.ai",
  },
  {
    id: 57,
    name: "Firework",
    logo: "https://company-images.partnerstack.com/file_w9CCBFytGCPVzQwhBP7A.png",
    category: "Marketing",
    summary:
      "Brings the in-person shopping experience online to increase conversions through Shoppable Short Video, Digital Showrooms, and One-to-one Virtual Shopping.",
    features: ["Video commerce", "Unlimited uploads", "Custom branding", "Auto populate products", "QR code support"],
    website: "https://firework.com",
  },
  {
    id: 58,
    name: "Plesk",
    logo: "https://company-images.partnerstack.com/file_PVXSycDHN0wQNbh7fe6e.jpeg",
    category: "Automation",
    summary:
      "Leading web hosting control panel. Helps hosting providers, agencies and developers easily manage websites, WordPress, email, DNS and databases from one dashboard.",
    features: ["Website management", "WordPress toolkit", "Email management", "DNS management", "Database management"],
    website: "https://plesk.com",
  },
  {
    id: 59,
    name: "McAfee",
    logo: "https://media.mcafeeassets.com/content/dam/npcld/ecommerce/en/company-logo/McAfeeHzRed.svg",
    category: "Antivirus",
    summary:
      "Comprehensive antivirus and security solution for desktop and mobile devices, protecting families across Windows and Mac platforms with advanced threat detection.",
    features: ["Real-time protection", "Family plans", "Multi-device support", "Windows & Mac", "Mobile security"],
    website: "https://uwahh.com/af?o=5ee1de098f4170dfc71741c2c1445f53:6c1ac9efbd69cbd39fbbe6317c8974b1&cid=your clickid&subid=your subid",
  },
  {
    id: 60,
    name: "Avast Ultimate Security",
    logo: "https://www.avast.com/content/dam/avast/logo/Default.svg",
    category: "Antivirus",
    summary:
      "Ultimate security suite for mobile devices offering comprehensive protection against malware, phishing, and online threats with advanced privacy features.",
    features: ["Mobile security", "Malware protection", "Phishing protection", "Privacy tools", "Real-time scanning"],
    website: "https://uwahh.com/af?o=fedd8069f723d23e0e9c17b71d394ccd:b7638e3b569d9210a7dea20f9ec765f2&cid=&subid=",
  },
  {
    id: 61,
    name: "Avira Prime",
    logo: "https://play-lh.googleusercontent.com/o8fk6tJ2jc4OKXNPw58fiJ0dIx-VQ-ZHLeChG5A9h8H84hmGFtMALGaRJG47SAaqpJM",
    category: "Antivirus",
    summary:
      "Premium antivirus solution with 40% discount, offering complete protection for web and mobile devices with advanced security features.",
    features: ["Web protection", "Mobile security", "Real-time scanning", "Privacy protection", "System optimization"],
    website: "https://yohch.com/af?o=54209b3bcced0e569de86c812e04d35f:5b1bed371b836e125d0674215aefec10&cid=&subid=",
  },
  {
    id: 62,
    name: "Surfshark Antivirus",
    logo: "https://i.pcmag.com/imagery/reviews/04QygPlFMBIJRVMggN25qC7-1..v1731441505.png",
    category: "Antivirus",
    summary:
      "Global antivirus protection solution providing comprehensive security for devices worldwide with advanced threat detection and removal capabilities.",
    features: ["Global coverage", "Threat detection", "Real-time protection", "Device security", "Malware removal"],
    website: "https://ahyiu.com/af?o=1fa304d9f64e93a4c0a6187aa75eea5f:715d5196642564269b182868c5f64415&cid=&subid=",
  },
  {
    id: 63,
    name: "Total AV",
    logo: "https://www.totalav.com/_r/c/6/_ptd/TotalBranding/Components/Logos/TAVLogo/TAVLogo/8bdce74b2c10-1/img/logo-alt.svg",
    category: "Antivirus",
    summary:
      "Complete antivirus solution for mobile and desktop devices, offering private email protection and comprehensive security across multiple platforms.",
    features: ["Multi-platform support", "Email protection", "Mobile & desktop", "Real-time scanning", "Privacy tools"],
    website: "https://ikueh.com/af?o=c383693e8c342fa400d551bcd5984c61:8d1fab641ae53b5439274da2e68d2fae&cid=&subid=",
  },
  {
    id: 64,
    name: "Unlocator",
    logo: "https://unlocator.com/wp-content/uploads/2019/05/logo.svg",
    category: "VPN",
    summary:
      "VPN and Smart DNS service offering 2-year plans for accessing geo-restricted content and maintaining online privacy with reliable connection speeds.",
    features: ["VPN service", "Smart DNS", "Geo-unblocking", "Privacy protection", "2-year plans"],
    website: "https://yohch.com/af?o=51bf1d22a61e5f68f2ccfb677c1a827a:71ba24e36f931c4da2f901852eb4c3a7&cid=&subid=",
  },
  {
    id: 65,
    name: "Surfshark VPN",
    logo: "https://images-eds-ssl.xboxlive.com/image?url=4rt9.lXDC4H_93laV1_eHHFT949fUipzkiFOBH3fAiZZUCdYojwUyX2aTonS1aIwMrx6NUIsHfUHSLzjGJFxxuO4Q1tKCo0hwnses7q5bXKPOQIUIh8PFc250Ah3CXwnWw6gU9e4mKqqxYoiPfUK.UE_6Or0G7A0dxLe2ckGS1M-&format=source",
    category: "VPN",
    summary:
      "Global VPN service providing secure and private internet access worldwide with unlimited device connections and advanced security features.",
    features: ["Global servers", "Unlimited devices", "No-logs policy", "Kill switch", "Multi-platform support"],
    website: "https://ikueh.com/af?o=381d1602f991a6e697a3497ca65c5487:902cb910943565a92c65fccaee8c4403&cid=&subid=",
  },
  {
    id: 66,
    name: "NordVPN",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/2/24/NordVPN_Logo_square.svg/1280px-NordVPN_Logo_square.svg.png",
    category: "VPN",
    summary:
      "Leading VPN service offering secure and private internet access with military-grade encryption, global server network, and advanced privacy features.",
    features: ["Military-grade encryption", "Global servers", "No-logs policy", "Kill switch", "Fast connections"],
    website: "https://ohfoi.com/af?o=2cb97a8bf7d3426353475ef216b8ff9d:2d7d4ab17a1653b5e8ecd3a11f448b39&cid=&subid=",
  },
  {
    id: 67,
    name: "Total Drive",
    logo: "https://www.totaldrive.com/_r/c/6/_ptd/Core/Brand/Logos/TDRLogo/TDRLogo/5f04fdc9f9e9-1/img/logo-all-white.svg",
    category: "Drive",
    summary:
      "Cloud storage solution for mobile and desktop devices, offering secure file storage, backup, and synchronization with private email and push notification features.",
    features: ["Cloud storage", "File backup", "Multi-device sync", "Mobile & desktop", "Email integration"],
    website: "https://ikueh.com/af?o=8ea24d61ebe58df9edf73aca5a12bf7f:37a304f401684e7ad56dab380c8b5d4a&cid=&subid=",
  },
]
